---
title: "Interactive nAWC"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
runtime: shiny
params: 
  data: "data/tp1-clusters_for_nawc.tsv"
---

```{r setup, include=FALSE}
suppressWarnings(suppressMessages(source("funcs.R")))
# rmarkdown::render("interactive_nawc.Rmd", params = list(data = "data/tp1-clusters_for_nawc.tsv"))
# Rscript -e "rmarkdown::render('interactive_nawc.Rmd', params = list(data = 'data/tp1-clusters_for_nawc.tsv'))"
```

Column {.tabset data-width=200}
-----------------------------------------------------------------------

### Data prep

```{r}
# takes less than a minute
outdir <- "outputs/summary/"
process(input_file = params$data, outdir, delimiter = "\t")
```


```{r}
a2 <- read.table("outputs/summary/stats.tsv", sep = "\t", header = TRUE) %>% 
  as_tibble() %>% add_column(Selected.for.Analysis = 0)
a2$Neighbour.AWC[is.na(a2$Neighbour.AWC)] <- 0
```
  curveNumber pointNumber   x        y
1           0         581 582 0.999969

```{r}
numericInput("plot1", "Significant change filtering", min = 0, max = 1, value = 0.95, step = 0.01)
```


```{r}
# Hover over a point to see details: 
# renderPrint({
#   d <- event_data("plotly_hover", source = "a")
#   if (!is.null(d)) {d}
# })
```

Click on a point in the plot to see details: 
```{r}
DT::renderDataTable({
  d <- event_data("plotly_click", source = "a")
  if (!is.null(d)) {
    x1 <- as.data.frame(d)
    df <- a2 %>% filter(Threshold == x1$x)
    DT::datatable(df)
  }
})
```


Column {data-width=800}
-----------------------------------------------------------------------

### nAWC plot

```{r}
renderPlotly({
  # differences x[i+1] - x[i]
  y4 <- which(diff(sign(diff(a2$Neighbour.AWC))) > 0) + 1
  # find the points that shrank from the left and grew to the right, note the indexing starts from 0
  pt <- a2[y4,] %>% filter(Neighbour.AWC <= input$plot1)
  a2$Selected.for.Analysis[a2$Threshold %in% pt$Threshold] <- 1
  
  # write.table(a2, file = file.path(outdir, "stats_with_analysis.tsv"), 
  #             sep = "\t", quote = FALSE, row.names = FALSE)
  
  plot_ly(a2, x = ~Threshold, y = ~Neighbour.AWC, name = "nAWC", 
          type = "scatter", mode = "lines", color = I("black"), 
          hovertemplate = "Threshold %{x}<br>nAWC: %{y:.3f}", source = "a") %>% 
    add_trace(data = pt, x = ~Threshold, y = ~Neighbour.AWC, 
              name = paste0("Significant<br>change<br>( <= ", input$plot1, " )"), 
              mode = "markers", color = I("purple"), size = I(30), 
              hovertemplate = "Threshold %{x}<br>nAWC: %{y:.3f}<extra>nAWC</extra>")
})
```

### nAWC plot {.tabset data-width=200}
```{r}

  
  
  # output$brushing <- renderPrint({
  #   d <- event_data("plotly_brushing")
  #   if (is.null(d)) "Brush extents appear here (double-click to clear)" else d
  # })
  # 
  # output$selecting <- renderPrint({
  #   d <- event_data("plotly_selecting")
  #   if (is.null(d)) "Brush points appear here (double-click to clear)" else d
  # })
  # 
  # output$brushed <- renderPrint({
  #   d <- event_data("plotly_brushed")
  #   if (is.null(d)) "Brush extents appear here (double-click to clear)" else d
  # })
  # 
  # output$selected <- renderPrint({
  #   d <- event_data("plotly_selected")
  #   if (is.null(d)) "Brushed points appear here (double-click to clear)" else d
  # })
```

