---
title: "Overview"
output: 
  html_document:
    code_fold: hide
runtime: shiny
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
source("functions/base_functions.R")
source("functions/processing_functions.R")
library(ggplot2)
library(plotly)
library(DT)
library(flexdashboard)

time1_raw <- "data/timepoint1_data.csv" %>% readBaseData(., 1)
time2_raw <- "data/timepoint2_data.csv" %>% readBaseData(., 2)
heights <- colnames(time1_raw)[-1]
```

```{r}
renderUI({
  selectInput(inputId = "sel_height", label = "Select height to analyze", choices = heights, selected = heights[10])
})
```

```{r}
user <- reactiveValues(h = NULL, cl = NULL)
observe({user$h <- input$sel_height})
observe({user$cl <- input$sel_cluster[1]})
observe({user$clust2 <- input$sel_cluster[2]})
```

### Growth for all TP1 clusters at the selected height (tracked and matched to corresponding TP2 clusters)
```{r}
renderDataTable({
  req(user$h)
  h <- user$h
  # h <- heights[10]
  b1 <- readRDS(paste0("outputs/with_growth_rate/h", h, ".Rds"))
  b1$flag <- b1$flag - 1
  b1 %>% set_colnames(c("TP1 height", "TP1 cluster", "TP1 cluster size", 
                        "TP2 height", "TP2 cluster", "TP2 cluster size", 
                        "Number of novels in the TP2 match",
                        "Number of identical clusters before this one (at first height)", 
                        "ID", "Number of TP2 heights through which this cluster has existed", 
                        "Growth = (TP2 C.S. - TP1 C.S.) / (TP1 C.S)", 
                        "b / growth = (Number of novels) / (Growth rate)")) %>% 
    DT::datatable(., caption = paste0("Growth rates of all TP1_h", h, " clusters at all TP2 heights"), 
                  fillContainer = TRUE, filter = "top", rownames = FALSE, 
                  options = list(pageLength = 1635, dom = "tipf", scrollY = "500px", 
                                 columnDefs = list(list(className = "dt-center", targets = 1:11)))) %>% 
    formatStyle(columns = 1:11, fontSize = '120%')
}, server = TRUE)
```

```{r}
# a1 <- readRDS("outputs/with_growth_rate/h200.Rds")
# a2 <- a1 %>% filter(tp1_cl == 2) %>% arrange(tp2_h, tp2_cl)
# ggplot(a2, aes(x = tp2_h, y = tp2_cl_size)) + geom_point()
# ggplot(a2, aes(x = tp2_h, y = actual_growth_rate)) + geom_point()
# ggplot(a2, aes(x = tp2_h, y = b_ov_growth)) + geom_point()
```

```{r}
renderUI({
  req(user$h)
  h <- user$h
  # h <- heights[10]
  b1 <- readRDS(paste0("outputs/with_growth_rate/h", h, ".Rds"))
  b1$flag <- b1$flag - 1
  tp1_clusters <- b1$id %>% unique()
  
  # sel_cluster <- tp1_clusters[2:4]
  selectInput(inputId = "sel_cluster", label = paste0("Select three TP1 clusters (at height ", h, ") to analyze"), 
              multiple = TRUE, 
              choices = tp1_clusters, selected = c(tp1_clusters[2], tp1_clusters[3], tp1_clusters[4]))
})
```

### Growth of the selected TP1 cluster at all TP2 heights

```{r}
renderDataTable({
  req(user$h); req(user$cl)
  h <- user$h
  clust <- user$cl[1]
  # clust <- sel_cluster[1]
  c1 <- readRDS(paste0("outputs/with_growth_rate/h", h, ".Rds")) %>% 
    filter(id == clust) %>% arrange(-b_ov_growth)
  c1$flag <- c1$flag - 1
  top_pt <- c1[which.max(c1$b_ov_growth),]
  others <- setdiff(c1$tp2_h, top_pt$tp2_h)
  
  c1 %>% set_colnames(c("TP1 height", "TP1 cluster", "TP1 cluster size", 
                        "TP2 height", "TP2 cluster", "TP2 cluster size", 
                        "Number of novels", 
                        "Number of identical clusters before this one (at first height)", "ID", 
                        "Number of TP2 heights through which this cluster has existed", 
                        "Growth = (TP2 C.S. - TP1 C.S.) / (TP1 C.S)", 
                        "b / growth = (Number of novels) / (Growth rate)")) %>% 
  DT::datatable(., #caption = "Growth rates of this TP1 cluster at all TP2 heights", 
                fillContainer = TRUE, filter = "top", rownames = FALSE, 
                options = list(pageLength = 1635, dom = "tipf", scrollY = "500px", 
                               columnDefs = list(list(className = "dt-center", targets = 1:11)))) %>% 
    formatStyle('TP2 height', target = 'row', 
                backgroundColor = styleEqual(c(top_pt$tp2_h, others), c('lightblue', rep('white', length(others))))) %>% 
    formatStyle(columns = 1:12, fontSize = '120%')
}, server = TRUE)
```

```{r}
renderPlotly({
  req(user$h); req(user$cl)
  h <- user$h
  clust <- user$cl[1]
  # h <- heights[10]
  # clust <- "TP1_h9_c2"
  c1 <- readRDS(paste0("outputs/with_growth_rate/h", h, ".Rds")) %>% filter(id == clust)
  c1$flag <- c1$flag - 1
  top_pt <- c1[which.max(c1$b_ov_growth),]
  
  # cl <- onecluster$id %>% unique()
  g1 <- ggplot(c1, aes(x = tp2_h, y = b_ov_growth)) + geom_point(size = 1) + 
    geom_point(data = top_pt, aes(x = tp2_h, y = b_ov_growth), 
               color = "black", fill = "lightblue", size = 4, shape = 23) + 
    xlab("Time point 2 thresholds") + ylab("Growth 'acceleration'") + 
    ggtitle(paste0("b / 'growth' of ", clust, " from TP1 to TP2"))
  ggplotly(g1)
})
```

```{r}
renderDataTable({
  req(user$h); req(user$cl)
  h <- user$h
  clust <- user$cl[1]
  clust <- sel_cluster[2]
  c1 <- readRDS(paste0("outputs/with_growth_rate/h", h, ".Rds")) %>% 
    filter(id == clust) %>% arrange(-b_ov_growth)
  c1$flag <- c1$flag - 1
  top_pt <- c1[which.max(c1$b_ov_growth),]
  others <- setdiff(c1$tp2_h, top_pt$tp2_h)
  
  c1 %>% set_colnames(c("TP1 height", "TP1 cluster", "TP1 cluster size", 
                        "TP2 height", "TP2 cluster", "TP2 cluster size", 
                        "Number of novels", 
                        "Number of identical clusters before this one (at first height)", "ID", 
                        "Number of TP2 heights through which this cluster has existed", 
                        "Growth = (TP2 C.S. - TP1 C.S.) / (TP1 C.S)", 
                        "b / growth = (Number of novels) / (Growth rate)")) %>% 
  DT::datatable(., #caption = "Growth rates of this TP1 cluster at all TP2 heights", 
                fillContainer = TRUE, filter = "top", rownames = FALSE, 
                options = list(pageLength = 1635, dom = "tipf", scrollY = "500px", 
                               columnDefs = list(list(className = "dt-center", targets = 1:11)))) %>% 
    formatStyle('TP2 height', target = 'row', 
                backgroundColor = styleEqual(c(top_pt$tp2_h, others), c('red', rep('white', length(others))))) %>% 
    formatStyle(columns = 1:12, fontSize = '120%')
}, server = TRUE)
```

```{r}
renderPlotly({
  req(user$h); req(user$cl)
  h <- user$h
  clust <- user$cl[1]
  # h <- heights[10]
  # clust <- "TP1_h9_c2"
  c1 <- readRDS(paste0("outputs/with_growth_rate/h", h, ".Rds")) %>% filter(id == clust)
  c1$flag <- c1$flag - 1
  top_pt <- c1[which.max(c1$b_ov_growth),]
  
  # cl <- onecluster$id %>% unique()
  g1 <- ggplot(c1, aes(x = tp2_h, y = b_ov_growth)) + geom_point(size = 1) + 
    geom_point(data = top_pt, aes(x = tp2_h, y = b_ov_growth), 
               color = "black", fill = "red", size = 4, shape = 23) + 
    xlab("Time point 2 thresholds") + ylab("Growth 'acceleration'") + 
    ggtitle(paste0("b / 'growth' of ", clust, " from TP1 to TP2"))
  ggplotly(g1)
})
```

### The TP1-TP2 cluster pairs with the 'most' growth, for all clusters at the selected TP1 height

```{r}
# renderDataTable({
#   req(user$h); req(user$cl)
#   h <- user$h
#   c1 <- readRDS(paste0("outputs/best_growth_per_clust/h", h, ".Rds"))
#   c1$flag <- c1$flag - 1
#   clust <- user$cl
#   others <- setdiff(c1$id, clust)
#   
#   c1 %>% set_colnames(c("TP1 height", "TP1 cluster", "TP1 cluster size", 
#                         "TP2 height", "TP2 cluster", "TP2 cluster size", 
#                         "Number of novels", 
#                         "Number of identical clusters before this one (at first height)", "ID", 
#                         "Number of TP2 heights through which this cluster has existed", 
#                         "Growth = (TP2 C.S. - TP1 C.S.) / (TP1 C.S)", 
#                         "b / growth = (Number of novels) / (Growth rate)")) %>% 
#     DT::datatable(., #caption = paste0("The TP1-TP2 cluster pairs with the 'most' growth, for all TP1_h", h, " clusters"), 
#                   fillContainer = TRUE, filter = "top", rownames = FALSE, 
#                   options = list(pageLength = nrow(c1), dom = "tipf", scrollY = "500px", 
#                                  columnDefs = list(list(className = "dt-center", targets = 1:5)))) %>% 
#     formatStyle('ID', target = 'row', 
#                 backgroundColor = styleEqual(c(clust, others), c('lightblue', rep('white', length(others))))) %>% 
#     formatStyle(columns = 1:12, fontSize = '120%')
# }, server = FALSE)
```

```{r}
### The TP1-TP2 cluster pairs with the 'most' growth, for all TP1 clusters at all TP1 heights
# renderDataTable({
#   req(user$cl); req(user$h)
#   metrics <- readRDS("outputs/results_summary.Rds")
#   m <- metrics %>% set_colnames(c("tp1_h", "tp1_cl", "tp1_cl_size", "tp2_h", "tp2_cl",
#                                   "tp2_cl_size", "num_novels", "flag", "id", "flagged_heights",
#                                   "prop_inc", "b_ov_growth", "adap_thresh", "fold_change"))
#   m$flag <- m$flag - 1
#   clust <- user$cl
#   h <- user$h
#   partA <- m %>% filter(id == clust)
#   partB <- m %>% filter(id != clust) %>% filter(tp1_h == h)
#   partC <- m %>% filter(tp1_h != h)
#   
#   toshow <- bind_rows(partA, partB) %>% bind_rows(., partC)
#   others <- setdiff(toshow$id, clust)
#   toshow %>% set_colnames(., colnames(metrics)) %>% 
#     DT::datatable(., fillContainer = TRUE, filter = "top", rownames = FALSE,
#                 options = list(pageLength = 1000, dom = "tipf", scrollY = "500px",
#                                  columnDefs = list(list(className = "dt-center", targets = 1:13)))) %>%
#     formatStyle(columns = 1:13, fontSize = '120%')
# })
```


```{r}
# formatStyle("ID", target = "row",
    #             backgroundColor = styleEqual(c(clust, others), c('lightblue', rep('white', length(others))))) %>%

### Chart A2
### Chart A1
# renderPlotly({
#   req(user$h)
#   h <- user$h
#   # the most cluster growth for each TP1 cluster, at threshold h
#   c1 <- readRDS(paste0("outputs/best_growth_per_clust/h", h, ".Rds"))
#   g2 <- ggplot(c1, aes(x = tp1_cl, y = b_ov_growth)) + geom_point()
#   ggplotly(g2)
# })
```

